export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_AUTH_ERROR: 'SET_AUTH_ERROR',
	SET_AUTH_CHECKED: 'SET_AUTH_CHECKED',

	SET_LOADING: 'SET_LOADING',

	CART_SET: 'CART_SET',
	CART_CLEAR: 'CART_CLEAR',
	CART_SET_ERROR: 'CART_SET_ERROR',

	SET_PRODUCTS: 'SET_PRODUCTS',
	ADD_PRODUCT: 'ADD_PRODUCT',
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	DELETE_PRODUCT: 'DELETE_PRODUCT',
	SET_PRODUCT_ERROR: 'SET_PRODUCT_ERROR',

	SET_CATEGORIES: 'SET_CATEGORIES',
	ADD_CATEGORY: 'ADD_CATEGORY',
	UPDATE_CATEGORY: 'UPDATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',
	SET_CATEGORY_ERROR: 'SET_CATEGORY_ERROR',

	SET_USERS: 'SET_USERS',
	ADD_USER: 'ADD_USER',
	UPDATE_USER: 'UPDATE_USER',
	DELETE_USER: 'DELETE_USER',
	SET_USER_ERROR: 'SET_USER_ERROR',
};
